### PR TITLE
Added support to use user roles for access to resource

### PR DESCRIPTION
**Pull request by SteveMeskers**

### CODE REVIEW

**Comment by milagan** [comment]
@SteveMeskers , is the role configuration per `Route`? For example, can I configure the following

Only Developer Role has access to `/traefik`
Developer, Administrator, and Field Service have access to `/wiramaX`

**Comment by SteveMeskers** [comment]
> @SteveMeskers , is the role configuration per `Route`? For example, can I configure the following
> 
> Only Developer Role has access to `/traefik` Developer, Administrator, and Field Service have access to `/wiramaX`

The configuration is for any router that this middleware is used for. In your example you would need to have 2 instances of `traefik-forward-auth` running to handle both routes. 1 instance will only allow the roles defined for any `Route` that it is used with

**Review by milagan — APPROVED** [review]
Approving based on the support that Steve describes.

**Comment by milagan** [comment]
@kmaheshbabu-ckpt , are we supporting roles for the Mock-up store installation?

**Pull request merged**
